[tool.black]
skip-string-normalization = true
line-length = 100
exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | setup.py           # also separately exclude a file named foo.py in
                       # the root of the project
)
'''